[build]
  command = "./build-netlify.sh"
  publish = "build"
  functions = ".netlify/functions-internal"

[dev]
  command = "npm run dev"
  port = 5173
  targetPort = 5173

# Redirect all URLs to the SvelteKit app
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/render"
  status = 200

# Set environment variables
[build.environment]
  NODE_VERSION = "18.17.0"

# Set up scheduled functions (similar to cron jobs)
[functions."scheduled-cleanup"]
  schedule = "0 5 * * *"

# Handle 404 errors
[[redirects]]
  from = "/*"
  to = "/404"
  status = 404
