# This is a fallback netlify.toml file that will be copied to the build directory

# Redirect all URLs to the SvelteKit app
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/render"
  status = 200

# Handle 404 errors
[[redirects]]
  from = "/*"
  to = "/404"
  status = 404
